version: '3'
services:
  nodejs:
    build: .
    volumes: 
      - ".:/usr/src/app"
    ports:
      - "80:3000"
    restart: always
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"