version: '3.3'
services:
    app:
        build: ./
        image: binilj04/flask-mysql:0.1
        depends_on:
          - db
        ports:
          - "5000:5000"
    db:
        image: mysql
        restart: always
        ports:
            - 32000:3306
        volumes:
            - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypaswd
    
volumes:
    mysql-data: {}
