version: '3.7'
services:
  php:
    container_name: php73
    image: php:7.3-apache
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: my_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    depends_on:
      - mysql
    ports:
      - "30002:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST= mysql
      - PMA_PORT=3306
    container_name: phpmyadmin-app

