version: '3.7'
services:
  php:
    container_name: php
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "30001:80"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=my_db
      - DB_USERNAME=db_user
      - DB_PASSWORD=password
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    depends_on:
      - mysql
    ports:
      - "30002:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST= mysql
      - PMA_PORT=3306
    container_name: phpmyadmin-app

